### ISSUE TITLE
Missing Color Schemes

### ISSUE THREAD

**Issue by lukepierotti** [d3/d3-scale-chromatic#10]
Hi I've been upgrading a lot of d3v3 code up to v4 and I noticed that there apparently is no schemeCategory20() or schemeCategory20c() functions in d3-scale-chromatic. The CHANGES.md however mentions that these do exist and are part of the namespace flattening.

See: https://github.com/d3/d3/blob/master/CHANGES.md#scales-d3-scale

Do they exist? if not I would suggest an edit to the CHANGES.md to remove the section that states that they are available in v4. Thanks.

**Comment by mbostock** [comment]
This is covered in the release notes for the D3 5.0 prerelease:

https://github.com/d3/d3/releases/tag/v5.0.0

These changes will be copied over to the CHANGES.md when 5.0 is released (or possibly sooner).

If you are using d3@4, the twenty-color schemes are available in d3-scale@1 (not d3-scale-chromatic).

**Comment by lukepierotti** [comment]
Thanks for clearing it that up!
