### ISSUE TITLE
Add cividis color scale, a scheme for viewers with color vision deficiency

### ISSUE THREAD

**Issue by hollasch** [d3/d3-scale-chromatic#15]
The cividis scale is a derivative of the viridis scale, adjusted for viewers with color vision deficiency, and also for those with standard vision, but avoiding the errors common with rainbow-style schemes.

![cividis color scale](https://user-images.githubusercontent.com/1695496/37986572-710c0816-31c1-11e8-8135-8cfa7a9b62c3.png)

References:
- [256-color LUT](https://github.com/fiji/fiji/blob/master/luts/cividis.txt)
- [Scientific American article](https://www.scientificamerican.com/article/end-of-the-rainbow-new-map-scale-is-more-readable-by-people-who-are-color-blind/)
- _[A Simulation Color Table for Engineers with Color Vision Deficiency](https://www.comsol.com/blogs/a-simulation-color-table-for-engineers-with-color-vision-deficiency/)_
- [Optimizing colormaps with consideration for color vision deficiency to enable accurate interpretation of scientific data](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0199239)

**Comment by mbostock** [comment]
Here’s a quick demo:

https://beta.observablehq.com/@mbostock/cividis

**Comment by hollasch** [comment]
Sweet! Wish I could have found a continuous formula, but the 256 LUT is probably fine. Looks great Mike.

**Comment by mbostock** [comment]
I computed a fifth-order polynomial regression as a continuous approximation that seems to work well. It’ll be in the next release.

**Comment by hollasch** [comment]
Thanks Mike!
