### ISSUE TITLE
Add discrete color schemes for arbitrary counts

### ISSUE THREAD

**Issue by qwertystop** [d3/d3-scale-chromatic#19]
Currently, only a few interpolated color schemes have discrete equivalents, and those that do have a limited number of possible ranges. For example, `schemeYlGnBu` offers discrete schemes only for lengths 3 through 9, and `interpolateCool` has no discrete scheme.

I've got a fairly simple function which could resolve this:
```
  function buildDiscreteFromInterpolator(interpolator, count) {                                                  
    const discrete = []                                                                                          
    for (let i=0; i < count; i++) {                                                                                  
      discrete.push(interpolator(i/count))                                                                       
    }                                                                                                            
    return discrete                                                                                              
  }   
```
but from a quick look at the source, I'm not sure where to put it for an actual PR. Or, if this function is a poor fit for the job for some reason I am unaware of, possibly suggest an alternative?

**Comment by mbostock** [comment]
This exists already and it is called [d3.quantize](https://github.com/d3/d3-interpolate/blob/master/README.md#quantize).
