### ISSUE TITLE
Adding HSV colormap

### ISSUE THREAD

**Issue by loichuder** [d3/d3-scale-chromatic#34]
Hi there :wave: 

We have a user requesting the [HSV colormap](https://fr.mathworks.com/help/matlab/ref/hsv.html) in our project: https://github.com/silx-kit/h5web/issues/481. 

As we use d3-scale-chromatic for our colormaps, we thought it might be better to add it here if it is a colormap you are interested in having ?

**Comment by Fil** [comment]
Doesn't it look a bit similar to sinebow https://github.com/d3/d3-scale-chromatic#cyclical

**Comment by loichuder** [comment]
Similar but not exactly the same apparently: https://mpetroff.net/2019/08/discernibility-of-rainbow-colormaps/

As _Sinebow_ is the improved version of _HSV_, I would understand if you are not interested in having both.

**Comment by mbostock** [comment]
You can implement the angry rainbow by hand:

```js
function interpolateAngryRainbow(t) {
  return d3.hsl(t * 360, 1, .5);
}
```

Use of this color scheme is strongly discouraged so I do not want to include it as a built-in scheme. (Note that this uses HSL and not HSV, but there’s a separate issue for supporting the HSV color space in d3-color.)
