### ISSUE TITLE
Pastel diverging color scheme

### ISSUE THREAD

**Issue by jadfls** [d3/d3-scale-chromatic#40]
Hello,

I see 2 pastel categorical schemes but none in diverging. Are there diverging color schemes that only contain pastel colors? Or is there an easy way to create such a scheme?

btw. Using alpha on colors of an existing diverging scheme is not an option as my graphics need to overlap.

**Comment by mbostock** [comment]
All the color schemes are listed in the README. If you’d like to design your own color scheme (which isn’t generally recommended, because it’s hard to do well; most of D3’s color schemes come from ColorBrewer), you can take a look at d3-interpolate. https://github.com/d3/d3-interpolate
