### ISSUE TITLE
Add option for opacity/alpha

### ISSUE THREAD

**Issue by SlowMo24** [d3/d3-scale-chromatic#44]
I would like to have `rgba`-values as output. I cannot find that option so I guess this would need an extension to the existing color-getter-functions to accept an optional alpha-value?

**Comment by curran** [comment]
You could convert colors to RGBA format using [`d3.rgb`](https://github.com/d3/d3-color#rgb).

```js
const { r, g, b, opacity } = d3.rgb(color);
const formatted = `rgba(${r},${g},${b},${opacity})`;
```

**Comment by SlowMo24** [comment]
ah nice, thank you! I didn't know about that function (and solved it with string replacement, but this is nicer).
