### ISSUE TITLE
Is the PuOr scheme backwards?

### ISSUE THREAD

**Issue by jheer** [d3/d3-scale-chromatic#5]
`interpolatePuOr` and `schemePuOr` ramp from orange to purple. This behavior is different from all the other examples, where the order of colors matches the order of color names in the exported property name. In addition, ColorBrewer also ramps from purple (a default for low values) to orange (a default for high values). Not sure if this was intentional or not, so thought it worthwhile to add an issue.

**Comment by mbostock** [comment]
Looks like a mistake to me! Want to send a PR?

**Comment by jheer** [comment]
Opened a PR, closing this issue.
